[package]
name = "image_example"
version = "0.1.0"
authors = ["vivek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image={git="https://github.com/image-rs/image"}